name: WebAssembly Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch WebAssembly spec
        uses: actions/checkout@v4
        with:
            repository: 'WebAssembly/spec'
            fetch-depth: '1'
            path: 'spec'

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
            ocaml-compiler: "5.2"

      - name: Setup opam
        run: eval $(opam env)

      - name: Install build requirements
        run: opam install dune && dune --version

      - name: Build WebAssembly spec reference interpreter
        run: (cd ${{ github.workspace }}/spec/interpreter; make)
      - name: Convert WebAssembly spec tests to wasm files
        run: ls -l ${{ github.workspace }}/spec/test/core/